FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

EXPOSE 3000

CMD ["sh", "-c", "npx prisma generate && npx prisma db push --accept-data-loss --force-reset && npm run start:dev"]
