import { PrismaClient } from 'generated/prisma/client';
import { PlanCreateInput } from 'generated/prisma/models';

const plans: PlanCreateInput[] = [
  // Free Tier
  {
    id: 'tier-free',
    name: 'Free',
    type: 'FREE',
    description: 'Perfect for individuals starting out.',
    price: 0,
    currency: 'USD',
    interval: 'MONTH',
    isActive: true,
    isMostPopular: false,
    features: [
      { text: '1 Business Organization', included: true },
      { text: '1 Private Workspace', included: true },
      { text: '3 Projects per Workspace', included: true },
      { text: '50 Tasks per Project', included: true },
      { text: 'Up to 3 Team Members', included: true },
      { text: 'Role-based Access Control', included: true },
      { text: 'Activity History', included: false },
      { text: 'Advanced Analytics', included: false },
      { text: 'Audit Logs', included: false },
      { text: 'Export Audit Logs', included: false },
    ],
    limits: {
      maxOrganizations: 1,
      maxWorkspacesPerOrg: 1,
      maxProjectsPerWorkspace: 3,
      maxTasksPerProject: 50,
      maxMembersPerOrg: 3,
      auditLogRetentionDays: 0,
      isLogExportAvailable: false,
    },
    note: 'No credit card required (in beta)',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Pro Monthly
  {
    id: 'tier-pro',
    name: 'Pro',
    type: 'PRO',
    description: 'The standard for high-performance teams.',
    price: 12,
    currency: 'USD',
    interval: 'MONTH',
    isActive: true,
    isMostPopular: true,
    features: [
      { text: 'Everything in Free', included: true },
      { text: 'Up to 5 Workspaces per Organization', included: true },
      { text: 'Up to 3 Projects per Workspace', included: true },
      { text: 'Unlimited Tasks per Project', included: true },
      { text: 'Up to 15 Team Members', included: true },
      { text: '45-day Activity Archive', included: true },
      { text: 'Priority Email Support', included: true },
      { text: 'Export Audit Logs', included: false },
      { text: '24/7 Priority Support', included: false },
      { text: 'Advanced Analytics Suite', included: false },
    ],
    limits: {
      maxOrganizations: 1,
      maxWorkspacesPerOrg: 5,
      maxProjectsPerWorkspace: 3,
      maxTasksPerProject: null,
      maxMembersPerOrg: 15,
      auditLogRetentionDays: 45,
      isLogExportAvailable: false,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Pro Yearly
  {
    id: 'tier-pro-yearly',
    name: 'Pro',
    type: 'PRO',
    description: 'The standard for high-performance teams.',
    price: 12 * 12 * 0.9, // 10% discount for yearly,
    currency: 'USD',
    interval: 'YEAR',
    isActive: true,
    isMostPopular: true,
    note: 'Billed yearly at 10% discount',
    features: [
      { text: 'Everything in Free', included: true },
      { text: 'Up to 5 Workspaces per Organization', included: true },
      { text: 'Up to 3 Projects per Workspace', included: true },
      { text: 'Unlimited Tasks per Project', included: true },
      { text: 'Up to 15 Team Members', included: true },
      { text: '45-day Activity Archive', included: true },
      { text: 'Priority Email Support', included: true },
      { text: 'Export Audit Logs', included: false },
      { text: '24/7 Priority Support', included: false },
      { text: 'Advanced Analytics Suite', included: false },
    ],
    limits: {
      maxOrganizations: 1,
      maxWorkspacesPerOrg: 5,
      maxProjectsPerWorkspace: 3,
      maxTasksPerProject: null,
      maxMembersPerOrg: 15,
      auditLogRetentionDays: 45,
      isLogExportAvailable: false,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Business Monthly
  {
    id: 'tier-business',
    name: 'Business',
    type: 'BUSINESS',
    description: 'Scale your organization with advanced controls.',
    price: 24,
    currency: 'USD',
    interval: 'MONTH',
    isActive: true,
    isMostPopular: false,
    features: [
      { text: 'Everything in Pro', included: true },
      { text: 'Up to 5 Business Organizations', included: true },
      { text: 'Up to 10 Workspaces per Organization', included: true },
      { text: 'Up to 20 Projects per Workspace', included: true },
      { text: 'Unlimited Tasks per Project', included: true },
      { text: 'Up to 50 Team Members per Organization', included: true },
      { text: '90-day Activity Archive', included: true },
      { text: 'Export Audit Logs', included: true },
      { text: '24/7 Priority Support', included: true },
      { text: 'Advanced Analytics Suite', included: true },
    ],
    limits: {
      maxOrganizations: 5,
      maxWorkspacesPerOrg: 10,
      maxProjectsPerWorkspace: 20,
      maxTasksPerProject: null,
      maxMembersPerOrg: 50,
      auditLogRetentionDays: 90,
      isLogExportAvailable: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Business Yearly
  {
    id: 'tier-business-yearly',
    name: 'Business',
    type: 'BUSINESS',
    description: 'Scale your organization with advanced controls.',

    currency: 'USD',
    interval: 'YEAR',
    price: Math.round(24 * 12 * 0.88), // 12% discount
    note: 'Billed yearly at 12% discount',
    isActive: true,
    isMostPopular: false,
    features: [
      { text: 'Everything in Pro', included: true },
      { text: 'Up to 5 Business Organizations', included: true },
      { text: 'Up to 10 Workspaces per Organization', included: true },
      { text: 'Up to 20 Projects per Workspace', included: true },
      { text: 'Unlimited Tasks per Project', included: true },
      { text: 'Up to 50 Team Members per Organization', included: true },
      { text: '90-day Activity Archive', included: true },
      { text: 'Export Audit Logs', included: true },
      { text: '24/7 Priority Support', included: true },
      { text: 'Advanced Analytics Suite', included: true },
    ],
    limits: {
      maxOrganizations: 5,
      maxWorkspacesPerOrg: 10,
      maxProjectsPerWorkspace: 20,
      maxTasksPerProject: null,
      maxMembersPerOrg: 50,
      auditLogRetentionDays: 90,
      isLogExportAvailable: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tier-early-access',
    name: 'Early Access',
    type: 'EARLY_ACCESS',
    description:
      'Full power for early believers. High-octane productivity for free.',
    price: 0,
    currency: 'USD',
    interval: null,
    isActive: true,
    isMostPopular: false,
    features: [
      { text: '1 Business Organization', included: true },
      { text: 'Up to 5 Workspaces (Beta)', included: true },
      { text: 'Up to 3 Projects per Workspace (Beta)', included: true },
      { text: 'Unlimited Tasks (Beta)', included: true },
      { text: 'Up to 15 Team Members (Beta)', included: true },
      { text: '90-day Activity Logs (Beta)', included: true },
      { text: 'Role-based Access Control', included: true },
    ],
    limits: {
      maxOrganizations: 1,
      maxWorkspacesPerOrg: 5,
      maxProjectsPerWorkspace: 3,
      maxTasksPerProject: null,
      maxMembersPerOrg: 15,
      auditLogRetentionDays: 90,
      isLogExportAvailable: false,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export async function seedPlans(prisma: PrismaClient) {
  await prisma.plan.deleteMany();
  for (const plan of plans) {
    await prisma.plan.upsert({
      where: { id: plan.id },
      create: plan,
      update: plan,
    });
  }
  console.log('✅ Plans seeded successfully');
}
